name: "[中文] 想法 / 痛点"
description: 提交新的软件想法、问题或未满足需求。
title: "[想法] "
labels:
  - idea
body:
  - type: markdown
    attributes:
      value: |
        感谢分享。请尽量具体并基于真实场景描述。
        
        你可以使用英语、中文、法语或德语填写。
  - type: textarea
    id: pain-point
    attributes:
      label: 1. 痛点描述
      description: 当前具体哪里不方便？
      placeholder: 描述具体场景、当前流程以及卡点。
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: 2. 设想方案
      description: 你想象中的软件/功能是什么？
      placeholder: 描述关键流程、输入输出和预期体验。
    validations:
      required: true
  - type: input
    id: target-users
    attributes:
      label: 3. 目标用户
      description: 谁会使用它？
      placeholder: 例如：独立摄影师、大一新生、自由产品经理
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 4. 现有替代方案
      description: 你调研了哪些工具？为什么不够好？
      placeholder: 请附链接并写明具体不足。
    validations:
      required: true
  - type: dropdown
    id: support-needed
    attributes:
      label: 5. 你需要的支持
      description: 你当前最希望得到哪类帮助？
      multiple: true
      options:
        - 推荐现有工具
        - 招募开发协作者
        - 招募设计协作者
        - 招募产品/运营协作者
        - 方案/范围建议
    validations:
      required: true
  - type: checkboxes
    id: policy-check
    attributes:
      label: Checklist
      options:
        - label: 我理解发布在这里的想法属于公开共享概念。
          required: true
        - label: 我已搜索过现有 Issue，这不是重复提交。
          required: true
